name: SimpleMobAdjustments
version: '${project.version}'
main: adhdmc.simplemobadjustments.SimpleMobAdjustments
api-version: 1.19
authors: [ Rhythmic, Peashooter101 ]
description: Sometimes, you just want more control.
